#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

from src.interpreter import interpret_file
from src.repl import repl

if len(sys.argv) > 1:
    print(interpret_file(sys.argv[1]))
else:
    repl()
